name: Run Tests

on:
  pull_request:
    branches:
      - main # Déclencher la pipeline pour les pull requests vers la branche main
  push:
    branches:
      - main # Déclencher la pipeline pour les pushs vers la branche main

jobs:
  test:
    runs-on: ubuntu-latest # Exécuter sur une machine virtuelle Ubuntu

    steps:
    # Étape 1 : Récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Node.js (si vous travaillez sur un projet Node.js)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Utiliser Node.js version 16

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: npm install

    # Étape 4 : Exécuter les tests
    - name: Run Tests
      run: npm test

    # Étape 5 (Optionnel) : Télécharger les résultats des tests comme artefacts
    - name: Upload Test Results (Optional)
      if: always() # Cette étape s'exécute même si les tests échouent
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-results # Dossier contenant les résultats des tests (modifiez selon vos besoins)
